"""Init Database Model

Revision ID: a8a56935ed6e
Revises: 
Create Date: 2026-02-22 23:35:43.487267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a8a56935ed6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grouptest',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('nama_group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('metodetest',
    sa.Column('metode_id', sa.Uuid(), nullable=False),
    sa.Column('nama_metode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jenis_metode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail_metode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('metode_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metodetest')
    op.drop_table('grouptest')
    # ### end Alembic commands ###
